upstream php_backend {
    server php:9000;  # Если у вас контейнер с PHP-FPM называется php и работает на порту 9000
}

server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;
    charset utf-8;
    client_max_body_size 5M;
    server_tokens off;

    # Главная локация, проксируем на PHP (например, Symfony)
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Проксирование запросов на PHP
    location ~ \.php$ {
        fastcgi_pass php_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        include fastcgi_params;
    }

    # Обслуживание статических файлов
    location /static/ {
        alias /app/public/static/;  # Путь к папке с вашими статическими файлами
        expires 15d;
    }

    location /media/ {
        alias /app/public/media/;  # Путь к папке с медиафайлами
        expires 7d;
    }

    # Логирование ошибок
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
