controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login

#app.swagger_ui:
#  path: /api
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#easy_admin_bundle:
#  resource: ../src/Controller/Admin
#  type: attribute
#  prefix: /admin

team_controllers:
  resource: ../src/Controller/Team
  prefix: /team
  type: attribute


player_controllers:
  resource: ../src/Controller/Player
  prefix: /player
  type: attribute

game_controllers:
  resource: ../src/Controller/Game
  prefix: /game
  type: attribute

tourney_controllers:
  resource: ../src/Controller/Tourney
  prefix: /tourney
  type: attribute